package FinalMaturitaCodes;

import java.util.Random;

/**
 *
 * @author Ondry
 */
public class _FourDigits extends javax.swing.JFrame {

    /**
     * Creates new form FourDigits
     */
    public _FourDigits() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vystupCisla = new javax.swing.JLabel();
        vystupText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cislo1 = new javax.swing.JSlider();
        cislo2 = new javax.swing.JSlider();
        cislo3 = new javax.swing.JSlider();
        cislo4 = new javax.swing.JSlider();
        lbl_cislo1 = new javax.swing.JLabel();
        lbl_cislo2 = new javax.swing.JLabel();
        lbl_cislo3 = new javax.swing.JLabel();
        lbl_cislo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vystupCisla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        vystupText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Zadejte cislo od 0 do 9999: ");

        jButton1.setText("ROLLUJ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Vygenerovana cisla:");

        cislo1.setMaximum(9);
        cislo1.setOrientation(javax.swing.JSlider.VERTICAL);
        cislo1.setValue(0);
        cislo1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cislo1StateChanged(evt);
            }
        });

        cislo2.setMaximum(9);
        cislo2.setOrientation(javax.swing.JSlider.VERTICAL);
        cislo2.setValue(0);
        cislo2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cislo2StateChanged(evt);
            }
        });

        cislo3.setMaximum(9);
        cislo3.setOrientation(javax.swing.JSlider.VERTICAL);
        cislo3.setValue(0);
        cislo3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cislo3StateChanged(evt);
            }
        });

        cislo4.setMaximum(9);
        cislo4.setOrientation(javax.swing.JSlider.VERTICAL);
        cislo4.setValue(0);
        cislo4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cislo4StateChanged(evt);
            }
        });

        lbl_cislo1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_cislo1.setText("0");

        lbl_cislo2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_cislo2.setText("0");

        lbl_cislo3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_cislo3.setText("0");

        lbl_cislo4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_cislo4.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vystupCisla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lbl_cislo1)
                                                    .addComponent(cislo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(cislo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl_cislo2))
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cislo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(34, 34, 34)
                                                        .addComponent(cislo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lbl_cislo3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lbl_cislo4)))))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(vystupText, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 416, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cislo2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cislo1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cislo3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cislo4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cislo1)
                    .addComponent(lbl_cislo2)
                    .addComponent(lbl_cislo3)
                    .addComponent(lbl_cislo4))
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(vystupCisla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(vystupText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        vystupCisla.setText("");
        String cislo = lbl_cislo1.getText() + lbl_cislo2.getText() + lbl_cislo3.getText() + lbl_cislo4.getText();
        int hodnota = Integer.valueOf(cislo);
        if (hodnota < 0 || hodnota > 9999) {
            vystupCisla.setText("");
            vystupText.setText("Spatne zadano");
        } else {
            //pocitej
            boolean vyhra = false;
            Random rd = new Random();
            int pole[] = new int[23];
            for (int i = 0; i < pole.length; i++) {
                pole[i] = -1;
            }
            //musime zajistit aby se do pole vygenerovanych intu neulozila duplicitni hodnota
            //pokud jiz v poli vygenerovany int je zmensi i o 1(opakuj praci s timto indexem)
            boolean obsahuje = false;
            int pom2;
            for (int i = 0; i < 23; i++) {
                pom2 = rd.nextInt(10000);
                for (int j = 0; j < pole.length; j++) {
                    if (pole[j] == pom2) {
                        obsahuje = true;
                    }
                }
                if (obsahuje == false) {
                    pole[i] = pom2;
                    if (pom2 == hodnota) {
                        vyhra = true;
                    }
                } else {
                    i--;
                }
                 obsahuje = false;
            }
            if (vyhra) {
                vystupText.setText("Vyhral jsi!");
            } else {
                vystupText.setText("Prohral jsi!");
            }
            for (int i = 0; i < pole.length; i++) {
                vystupCisla.setText(vystupCisla.getText() + pole[i] + ", ");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cislo1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cislo1StateChanged
        lbl_cislo1.setText(Integer.toString(cislo1.getValue()));
    }//GEN-LAST:event_cislo1StateChanged

    private void cislo2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cislo2StateChanged
        lbl_cislo2.setText(Integer.toString(cislo2.getValue()));
    }//GEN-LAST:event_cislo2StateChanged

    private void cislo3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cislo3StateChanged
        lbl_cislo3.setText(Integer.toString(cislo3.getValue()));
    }//GEN-LAST:event_cislo3StateChanged

    private void cislo4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cislo4StateChanged
        lbl_cislo4.setText(Integer.toString(cislo4.getValue()));
    }//GEN-LAST:event_cislo4StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_FourDigits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_FourDigits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_FourDigits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_FourDigits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _FourDigits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider cislo1;
    private javax.swing.JSlider cislo2;
    private javax.swing.JSlider cislo3;
    private javax.swing.JSlider cislo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_cislo1;
    private javax.swing.JLabel lbl_cislo2;
    private javax.swing.JLabel lbl_cislo3;
    private javax.swing.JLabel lbl_cislo4;
    private javax.swing.JLabel vystupCisla;
    private javax.swing.JLabel vystupText;
    // End of variables declaration//GEN-END:variables
}
